In [3]:
import numpy as np

1.ANSWER

In [4]:
n_arr = np.arange(2,50,3)
print(n_arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


2.ANSWER

In [10]:
lst1 = [2,30,4,54,69,1]
lst2 = [10,52,74,9,2,4]
n_arr = np.array([lst1,lst2])
print(np.sort(n_arr))

[[ 1  2  4 30 54 69]
 [ 2  4  9 10 52 74]]


3.ANSWER

In [12]:
n_arr = np.array([[89,54,63],[75,8,45],[4,78,20]])
print(n_arr)
print(n_arr.ndim)
print(n_arr.size)


[[89 54 63]
 [75  8 45]
 [ 4 78 20]]
2
9


4.ANSWER

In [45]:
n_arr1 = np.array([1,2,4,5,7,8,9,6,3,50])
n_arr2 = np.reshape(n_arr1,(2,5))
print(n_arr2)
print(n_arr1[np.newaxis:])

arr = np.expand_dims(n_arr1, axis=(2,0))
print(arr)

[[ 1  2  4  5  7]
 [ 8  9  6  3 50]]
[ 1  2  4  5  7  8  9  6  3 50]
[[[ 1]
  [ 2]
  [ 4]
  [ 5]
  [ 7]
  [ 8]
  [ 9]
  [ 6]
  [ 3]
  [50]]]


5.ANSWER

In [49]:
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])

print( np.hstack((n1, n2)))
print(np.vstack((n1,n2)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


6.ANSWER

In [55]:
nums = np.array([1, 1, 2, 3, 4, 4, 1])

(unique, counts) = numpy.unique(number_list, return_counts=True)
freq = np.asarray((unique, counts))
print(freq)

[[1 2 3 4]
 [3 1 1 2]]
